name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.18.2
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"    # ESLint 9 supports >=18.18; 20 is a safe LTS
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint
